### ISSUE TITLE
Add Support For SVN 1.8

### ISSUE THREAD

**Issue by opticyclic** [opticyclic/svntask#4]

**Comment by opticyclic** [comment]
According to the svnkit website
http://svnkit.com/download.php

SVNKit 1.8.5 is compatible both with Subversion 1.8 and Subversion 1.7 working copy formats. No upgrade is required for working copies in 1.7 format. 

Both SVNKit 1.7.12 and 1.8.5 support 1.6 and older working copy formats without need to upgrade.

So do we really need the different versions packaged?

**Comment by jdlaroche** [comment]
But the current bundled SVNKit version does not support Subversion 1.8. Can I just replace the jar and expect that nothing will break? If it is not the case, then a new version should be packaged...

**Comment by opticyclic** [comment]
You should be able to. A new release has it bundled now though.
